### ISSUE TITLE
Standalone + SSR

### ISSUE THREAD

**Issue by Judp0m** [FortAwesome/angular-fontawesome#407]
What is the support for Standalone (no modules) and Server Side Rendering?

Without the Standalone mode, icons show up properly in the server-generated version of my app.
With standalone, the icons are blank for the SSR page, and then get populated once the client takes over. So it flashes after a couple seconds of loading (load SSR page, no icons, load the app, bootstraps the app, then the icons show up).
This causes layout shifts and is obviously undesirable.

If it is supported, could we get a guide or clarity?
If not supported, consider that a feature request.

**Comment by devoto13** [comment]
> What is the support for Standalone (no modules) and Server Side Rendering?

Have never tested it, so not sure. Let's consider it a feature request to write a guide/test and fix it if needed.

**Comment by DominicWrege** [comment]
Standalone would be awesome

**Comment by msacket** [comment]
A similar problem for me is that the icons are initially displaying too large with the SSR.  A flash later, once the website hydrates client-side and the font-awesome CSS is injected, they shrink to the correct size.  For my particular use case, copying the relevant css to the main scss works around this issue:

```css
svg:not(:root).svg-inline--fa, svg:not(:host).svg-inline--fa {
    overflow: visible;
    box-sizing: content-box;
}
.svg-inline--fa {
    display: var(--fa-display, inline-block);
    height: 1em;
    overflow: visible;
    vertical-align: -0.125em;
}
```
